### ISSUE TITLE
InvalidPlistException: module 'plistlib' has no attribute 'Data'

### ISSUE THREAD

**Issue by afrade** [jfarley248/iTunes_Backup_Reader#14]
Hi! First I would like to thank you for your work
I'm having trouble running the script, I'm getting exceptions.
Can you please give some help? Thanks

- macOS
- python3
- have installed trough pip3: pathlib-revised; biplist; pycryptodome; construct; recreator; kaitaistruct
- encrypted backup

`
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/biplist/__init__.py", line 126, in readPlist
    result = reader.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/biplist/__init__.py", line 234, in parse
    return self.readRoot()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/biplist/__init__.py", line 248, in readRoot
    raise NotBinaryPlistException()
biplist.NotBinaryPlistException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/biplist/__init__.py", line 141, in readPlist
    result = wrapDataObject(result, for_binary=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/biplist/__init__.py", line 154, in wrapDataObject
    elif isinstance(o, (bytes, plistlib.Data)) and for_binary:
AttributeError: module 'plistlib' has no attribute 'Data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[userFolder]/iTunes_Backup_Reader/iTunes_Backup_Reader.py", line 211, in <module>
    main()
  File "[userFolder]/iTunes_Backup_Reader/iTunes_Backup_Reader.py", line 157, in main
    plist_parser.parsePlists(input_dir, output_dir, out_type, decrypt, logger)
  File "[userFolder]/iTunes_Backup_Reader/helpers/plist_parser.py", line 194, in parsePlists
    backups, apps = readPlists(status_plist_path, manifest_plist_path, info_plist_path, logger, output_dir)
  File "[userFolder]/iTunes_Backup_Reader/helpers/plist_parser.py", line 141, in readPlists
    info_plist = readPlist(info_plist_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/biplist/__init__.py", line 143, in readPlist
    raise InvalidPlistException(e)
biplist.InvalidPlistException: module 'plistlib' has no attribute 'Data'
`

**Comment by prancinghog** [comment]
Hello @jfarley248,

Thank you for this library. I am having the same error as @afrade.

I was wondering if you had a suggestion, please.

**Comment by Andi-The** [comment]
I think the issue is caused by the biplist library, which is not compatible with Python 3.9+. So you have to use an older python version.
