### ISSUE TITLE
manifestMbdbParser UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf5 in position 3: invalid start byte

### ISSUE THREAD

**Issue by johnfoxii** [jfarley248/iTunes_Backup_Reader#21]
iTunes_Backup_Reader.exe VERSION 4.0

Tried changing 

`.decode("utf-8","ignore")

_Reader-master\Oct-09-2017-800pm\KeyboardDomain
07-11 00:03 root         DEBUG    Successfully created path
Traceback (most recent call last):
  File "iTunes_Backup_Reader.py", line 211, in <module>
    main()
  File "iTunes_Backup_Reader.py", line 161, in main
    recreator.startRecreate(input_dir, output_dir, password, 0, logger)
  File "helpers\recreator.py", line 79, in startRecreate
    manifestMbdbParser.mbdbParser(manifest_mbdb_path, input_dir, output_dir, logger)
  File "helpers\manifestMbdbParser.py", line 53, in mbdbParser
    path = (record.Path.String).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf5 in position 3: invalid start byte
[12648] Failed to execute script iTunes_Backup_Reader

**Comment by thadude3** [comment]
try using decode('ISO-8859-1')  , that allowed me to decode but ended up with some wonky file names which failed to create the directories.
