### ISSUE TITLE
ImportError: cannot import name 'KaitaiStruct'

### ISSUE THREAD

**Issue by omhmega** [jfarley248/iTunes_Backup_Reader#7]
This is a normal unencrypted backup with only -i -o and -v parameters. I get: ImportError: cannot import name 'KaitaiStruct'

Kaitaistruct package is present in iTBR root. Running Python 3.6.5

Traceback (most recent call last):
  File "C:\temp\iTunes_Backup_Reader-4.0\iTunes_Backup_Reader.py", line 18, in <module>
    from helpers import plist_parser, recreator
  File "C:\temp\iTunes_Backup_Reader-4.0\helpers\recreator.py", line 17, in <module>
    from helpers import decryptor
  File "C:\temp\iTunes_Backup_Reader-4.0\helpers\decryptor.py", line 17, in <module>
    from kaitaistruct import KaitaiStruct, KaitaiStream, BytesIO
ImportError: cannot import name 'KaitaiStruct'

**Comment by jfarley248** [comment]
Looking into this now. Are you able to use the executable?

**Comment by omhmega** [comment]
> 
> 
> Looking into this now. Are you able to use the executable?

Didn't try the exe.
I used the previous version directly from Python just fine.

Great project, BTW. Thank you

**Comment by omhmega** [comment]
It seems that "from kaitaistruct import KaitaiStruct, KaitaiStream, BytesIO" is redundant as the kaitai lib is only referred to in the helpers/decryptor.py (code) and construct/core.py (comment) files. KaitaiStruct and KaitaiStream are not mentioned anywhere in the code (except the import line), and BytesIO is imported from the Python io library.
